from: markdown+tex_math_dollars+raw_attribute+inline_code_attributes+definition_lists+implicit_figures+citations+implicit_header_references
# yaml_metadata_block +grid_tables+pipe_tables+simple_tables
to: pdf
pdf-engine: xelatex
pdf-engine-opt: -shell-escape
standalone: true
fail-if-warnings: true
# Manually in report.md
# table-of-contents: true
# toc-depth: 2
number-sections: true
include-in-header: config/preamble.tex
dpi: 121
# filters:
# - pandoc-include-code