lang: ru-RU
# omit title
author: Кондраев Дмитрий
rights:  Creative Commons Non-Commercial Share Alike 3.0
# LaTeX
documentclass: article
geometry:
  - a4paper
  - top=2cm
  - bottom=2cm
  - left=2.5cm
  - right=2cm
fontsize: 12pt
fontenc: T2A
mainfont: XITS
sansfont: PT Sans
# monofont: JuliaMono
monofont: Cascadia Code
mathfont: XITS Math

secnumdepth: 3

bibliography: config/references.bib
# https://github.com/Darxor/CSL-GOST
citation-style: config/GOST_R_7011_numeric.csl
link-citations: true
# links-as-notes: true
hyperrefoptions:
- bookmarksdepth=10

colorlinks: true
linkcolor: blue
urlcolor: red
# toccolor: gray
